apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  template: 
    spec: 
      containers:
      - name: loadgenerator
        image: gcr.io/krm-nov27/cymbal-bank/release/loadgenerator:112afc7
        env:
        - name: LOG_LEVEL
          value: "info"